apiVersion: v1
kind: Service
metadata:
  labels:
    app: next
  name: next
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: next
  type: LoadBalancer
